//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisakaWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add this namespace for validation attributes

    public partial class Account
    {
        public int accountID { get; set; }

        [Required(ErrorMessage = "Account Name is required")]
        [StringLength(50, ErrorMessage = "Account Name must be at most 50 characters")]
        public string accountName { get; set; }

        [Required(ErrorMessage = "Account Password is required")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Password must be between 6 and 20 characters")]
        public string accountPassword { get; set; }

        public string customerID { get; set; }

        [Display(Name = "Created At")] // Optional: Add display name for better readability
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> createdAt { get; set; }

        [Display(Name = "Account Status")] // Optional: Add display name for better readability
        public Nullable<bool> account_status { get; set; }

        public virtual Customer Customer { get; set; }
    }
}

