//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HisakaWeb.Models
{
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [Required(ErrorMessage = "Product ID is required")]
        public string productID { get; set; }

        [Required(ErrorMessage = "Product Name is required")]
        [StringLength(100, ErrorMessage = "Product Name must be at most 100 characters")]
        public string productName { get; set; }

        [Required(ErrorMessage = "Product Price is required")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Product Price must be greater than 0")]
        public Nullable<double> productPrice { get; set; }

        [Required(ErrorMessage = "Product Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Product Quantity must be at least 1")]
        public Nullable<int> productQuantity { get; set; }

        [Required(ErrorMessage = "Product Category is required")]
        public string productCategory { get; set; }

        [Required(ErrorMessage = "Product Brand is required")]
        public string productBrand { get; set; }

        [Display(Name = "Created At")] // Optional: Add display name for better readability
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> createdAt { get; set; }

        public string productImage { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

